title: Maak een springplank-schakelaar
hero_image: images/banner.png
description: Hoe kan je een zelfgemaakte springplank-schakelaar aansluiten op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - 
    title: Maak een springplank-schakelaar
